title = "Jakub Pietrucha (mandross)"
baseURL = "https://mandross.dev/"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Jakub Pietrucha"
  description = "Welcome to my page"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "By Jakub Pietrucha"
    url = "https://github.com/mandross"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/mandross"
  [[params.socialIcons]]
    icon = "fab  fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/jakubpietrucha/"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:mail@mandross.dev"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 1

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
